// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://czkneolyucjkgkisgukt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6a25lb2x5dWNqa2draXNndWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjIyNTksImV4cCI6MjA3MDQ5ODI1OX0.ad5zG6D9LukOe5XFa4KDzmD5I_EsmkWGhHdPmfj5WkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
